# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"conv3x3x3": "00_res.ipynb",
         "downsample_basic_block": "00_res.ipynb",
         "BasicBlock": "00_res.ipynb",
         "Bottleneck": "00_res.ipynb",
         "ResNet": "00_res.ipynb",
         "resnet10": "00_res.ipynb",
         "resnet18": "00_res.ipynb",
         "resnet34": "00_res.ipynb",
         "resnet50": "00_res.ipynb",
         "resnet101": "00_res.ipynb",
         "resnet152": "00_res.ipynb",
         "resnet200": "00_res.ipynb",
         "open_npy": "01_MRI.ipynb",
         "MriTensorImage": "01_MRI.ipynb",
         "MRIVisionTransformer": "02_vit.ipynb"}

modules = ["core.py",
           "res.py",
           "MRI.py",
           "vit.py"]

doc_url = "https://robeson1010.github.io/EFF3D/"

git_url = "https://github.com/robeson1010/EFF3D/tree/{branch}/"

def custom_doc_links(name): return None
